/**
 * A fully typed Spock client with zero Spock-specific tooling.
 *
 * The schema is introspected from a running `spock run`; the types are
 * generated by graphql-codegen's client preset (`npm run generate`).
 * Everything below — nested selections, mutation variables, input
 * objects — is inferred; misspell a field and `npm run check` fails.
 */
import { graphql } from './gql'
import type { TypedDocumentString } from './gql/graphql'

const SPOCK_URL = process.env.SPOCK_URL ?? 'http://127.0.0.1:4000/graphql/v1'

/** A contract-derived error, matched by `code` (docs/spec/v0.md §6.1). */
class SpockError extends Error {
  code: string
  kind: string
  table: string | null
  fields: string[]
  /**
   * Partial data, when the response carried both. Mutations execute
   * serially, each in its own transaction — an earlier field's committed
   * write can arrive alongside a later field's error, and a client must
   * not lose it.
   */
  data: unknown

  constructor(
    err: {
      message: string
      extensions?: { code?: string; kind?: string; table?: string | null; fields?: string[] }
    },
    data: unknown = null,
  ) {
    super(err.message)
    this.code = err.extensions?.code ?? 'internal'
    this.kind = err.extensions?.kind ?? 'internal'
    this.table = err.extensions?.table ?? null
    this.fields = err.extensions?.fields ?? []
    this.data = data
  }
}

/** POST one operation; return `data` typed by the document. */
async function execute<TResult, TVariables>(
  query: TypedDocumentString<TResult, TVariables>,
  ...[variables]: TVariables extends Record<string, never> ? [] : [TVariables]
): Promise<TResult> {
  const response = await fetch(SPOCK_URL, {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ query, variables }),
  })
  const payload = (await response.json()) as {
    data?: TResult
    errors?: ConstructorParameters<typeof SpockError>[0][]
  }
  if (payload.errors?.length) throw new SpockError(payload.errors[0], payload.data ?? null)
  if (payload.data === undefined || payload.data === null) {
    throw new Error('no data in response')
  }
  return payload.data
}

// -- the feed: nested reverse relations, all inferred -----------------------

const FeedQuery = graphql(`
  query Feed {
    user {
      username
      post_by_author {
        caption
        like_by_post {
          user {
            username
          }
        }
      }
    }
  }
`)

// -- writes: input objects and scalars come from the generated types --------

const InsertUser = graphql(`
  mutation InsertUser($object: user_insert_input!) {
    insert_user_one(object: $object) {
      id
      username
      joined_at
    }
  }
`)

const UpdateBio = graphql(`
  mutation UpdateBio($id: uuid!, $set: user_set_input!) {
    update_user_by_pk(pk_columns: { id: $id }, _set: $set) {
      username
      bio
    }
  }
`)

const DeleteUser = graphql(`
  mutation DeleteUser($id: uuid!) {
    delete_user_by_pk(id: $id) {
      username
    }
  }
`)

const UsersQuery = graphql(`
  query Users {
    user(limit: 200) {
      id
      username
    }
  }
`)

// self-heal: a run that crashed between insert and cleanup leaves `nova`
// behind, and the next insert would trip user_username_taken
const leftover = (await execute(UsersQuery)).user.find((u) => u.username === 'nova')
if (leftover) {
  await execute(DeleteUser, { id: leftover.id })
  console.log('(cleaned up a leftover @nova from an interrupted run)')
}

const feed = await execute(FeedQuery)
for (const user of feed.user) {
  const posts = user.post_by_author
    .map((p) => `"${p.caption ?? '(untitled)'}" (${p.like_by_post.length} likes)`)
    .join(', ')
  console.log(`@${user.username}: ${posts || 'no posts'}`)
}

const created = await execute(InsertUser, {
  object: { username: 'nova', bio: 'typed end to end' },
})
console.log(`created @${created.insert_user_one.username} at ${created.insert_user_one.joined_at}`)

const updated = await execute(UpdateBio, {
  id: created.insert_user_one.id,
  set: { bio: 'still typed' },
})
console.log(`updated bio: ${updated.update_user_by_pk.bio}`)

// The contract's derived errors reach TypeScript as data: the code below
// was published in the schema (and in `GET /~contract`) before any request
// was made — clients match on it, they never parse messages.
try {
  await execute(InsertUser, { object: { username: 'maya' } })
} catch (e) {
  if (e instanceof SpockError && e.code === 'user_username_taken') {
    console.log(`rejected as expected: ${e.code} on ${e.table}.${e.fields.join(',')}`)
  } else {
    throw e
  }
}

// leave the seed as we found it, so the demo re-runs cleanly
await execute(DeleteUser, { id: created.insert_user_one.id })
console.log('cleaned up — run me again')
