//! The compiled contract (docs/spec/v0.md §6) — the interchange artifact.
//!
//! Everything a runtime or tool needs is in [`Contract`]; nothing refers back
//! to source text. Serialization shape is normative (§6).

use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Contract {
    /// Language version tag; `"v0"`.
    pub spock: String,
    pub tables: Vec<Table>,
    pub seed: Vec<SeedRow>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Table {
    pub name: String,
    /// Key field names, declaration order.
    pub key: Vec<String>,
    pub fields: Vec<Field>,
    /// Multi-field unique groups (single-field uniques live on the field).
    pub uniques: Vec<Vec<String>>,
    /// Derived errors (§6.1). Never hand-written.
    pub errors: Vec<DerivedError>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Field {
    pub name: String,
    #[serde(rename = "type")]
    pub ty: Type,
    pub optional: bool,
    pub unique: bool,
    pub default: Option<DefaultValue>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum Type {
    Text,
    Int,
    Bool,
    Timestamp,
    Uuid,
    /// The field holds the key of a row of `table`.
    Ref {
        table: String,
        on_delete: OnDelete,
    },
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum OnDelete {
    Restrict,
    Cascade,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum DefaultValue {
    /// UUIDv7 generated by the runtime at insert.
    Auto,
    /// UTC now captured by the runtime at insert.
    Now,
    Str {
        value: String,
    },
    Int {
        value: i64,
    },
    Bool {
        value: bool,
    },
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct DerivedError {
    pub code: String,
    pub kind: ErrorKind,
    pub fields: Vec<String>,
    pub status: u16,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ErrorKind {
    Key,
    Unique,
    Required,
    RefNotFound,
    Restricted,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct SeedRow {
    pub table: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub binding: Option<String>,
    pub fields: BTreeMap<String, SeedValue>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SeedValue {
    /// Reference to an earlier seed row's binding. Tried first: it is the
    /// only object-shaped seed value.
    Ref {
        #[serde(rename = "ref")]
        binding: String,
    },
    Str(String),
    Int(i64),
    Bool(bool),
}

impl Contract {
    pub fn table(&self, name: &str) -> Option<&Table> {
        self.tables.iter().find(|t| t.name == name)
    }

    /// Reference fields across the contract that point at `target`,
    /// as `(referencing table, referencing field)`.
    pub fn inbound_refs(&self, target: &str) -> Vec<(&Table, &Field)> {
        self.tables
            .iter()
            .flat_map(|t| t.fields.iter().map(move |f| (t, f)))
            .filter(|(_, f)| matches!(&f.ty, Type::Ref { table, .. } if table == target))
            .collect()
    }

    /// Resolve the *storage* type a value of `ty` bottoms out at, chasing
    /// reference chains. Key-cycle-free by the checker (E017).
    pub fn storage_type(&self, ty: &Type) -> StorageType {
        match ty {
            Type::Text | Type::Uuid | Type::Timestamp => StorageType::Text,
            Type::Int => StorageType::Integer,
            Type::Bool => StorageType::Integer,
            Type::Ref { table, .. } => {
                let target = self.table(table).expect("checked: ref target exists");
                let key_field = target.field(&target.key[0]).expect("checked: key exists");
                self.storage_type(&key_field.ty)
            }
        }
    }

    /// Resolve the *value* type a field bottoms out at — the type that
    /// governs wire validation. For refs this is the target key's type.
    pub fn value_type<'a>(&'a self, ty: &'a Type) -> &'a Type {
        match ty {
            Type::Ref { table, .. } => {
                let target = self.table(table).expect("checked: ref target exists");
                let key_field = target.field(&target.key[0]).expect("checked: key exists");
                self.value_type(&key_field.ty)
            }
            other => other,
        }
    }
}

impl Table {
    pub fn field(&self, name: &str) -> Option<&Field> {
        self.fields.iter().find(|f| f.name == name)
    }

    /// The key field, if the key is a single field.
    pub fn single_key(&self) -> Option<&Field> {
        match self.key.as_slice() {
            [only] => self.field(only),
            _ => None,
        }
    }

    /// Look up the derived error for a kind and field set (§6.1).
    pub fn error_for(&self, kind: ErrorKind, fields: &[&str]) -> Option<&DerivedError> {
        self.errors.iter().find(|e| {
            e.kind == kind
                && e.fields
                    .iter()
                    .map(String::as_str)
                    .eq(fields.iter().copied())
        })
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum StorageType {
    Text,
    Integer,
}

impl StorageType {
    pub fn sql(self) -> &'static str {
        match self {
            StorageType::Text => "TEXT",
            StorageType::Integer => "INTEGER",
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn contract_serde_roundtrip() {
        let contract = Contract {
            spock: "v0".into(),
            tables: vec![Table {
                name: "user".into(),
                key: vec!["id".into()],
                fields: vec![
                    Field {
                        name: "id".into(),
                        ty: Type::Uuid,
                        optional: false,
                        unique: false,
                        default: Some(DefaultValue::Auto),
                    },
                    Field {
                        name: "invited_by".into(),
                        ty: Type::Ref {
                            table: "user".into(),
                            on_delete: OnDelete::Restrict,
                        },
                        optional: true,
                        unique: false,
                        default: None,
                    },
                ],
                uniques: vec![],
                errors: vec![DerivedError {
                    code: "user_already_exists".into(),
                    kind: ErrorKind::Key,
                    fields: vec!["id".into()],
                    status: 409,
                }],
            }],
            seed: vec![SeedRow {
                table: "user".into(),
                binding: Some("maya".into()),
                fields: BTreeMap::from([
                    ("username".into(), SeedValue::Str("maya".into())),
                    (
                        "invited_by".into(),
                        SeedValue::Ref {
                            binding: "luis".into(),
                        },
                    ),
                ]),
            }],
        };

        let json = serde_json::to_string_pretty(&contract).unwrap();
        // normative shapes (§6)
        assert!(json.contains("\"kind\": \"uuid\""));
        assert!(json.contains("\"kind\": \"ref\""));
        assert!(json.contains("\"on_delete\": \"restrict\""));
        assert!(json.contains("\"kind\": \"auto\""));
        assert!(json.contains("\"ref\": \"luis\""));

        let back: Contract = serde_json::from_str(&json).unwrap();
        assert_eq!(back.tables[0].name, "user");
        assert!(matches!(
            back.seed[0].fields.get("invited_by"),
            Some(SeedValue::Ref { binding }) if binding == "luis"
        ));
        assert!(matches!(
            back.seed[0].fields.get("username"),
            Some(SeedValue::Str(s)) if s == "maya"
        ));
    }
}
