//! The compiled contract (docs/spec/v0.md §6) — the interchange artifact.
//!
//! Everything a runtime or tool needs is in [`Contract`]; nothing refers back
//! to source text. Serialization shape is normative (§6).

use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Contract {
    /// Language version tag; `"v0"`.
    pub spock: String,
    pub tables: Vec<Table>,
    /// Named wire shapes (fn returns). Additive under `spock: "v0"` —
    /// `default` keeps pre-record contract JSON deserializable.
    #[serde(default)]
    pub records: Vec<Record>,
    /// The deliberate surface: declared functions with SQL-escape bodies.
    /// Additive under `spock: "v0"`.
    #[serde(default)]
    pub fns: Vec<FnDef>,
    pub seed: Vec<SeedRow>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Table {
    pub name: String,
    /// Key field names, declaration order.
    pub key: Vec<String>,
    pub fields: Vec<Field>,
    /// Multi-field unique groups (single-field uniques live on the field).
    pub uniques: Vec<Vec<String>>,
    /// Cross-column row checks (RFD 0013): each names a field group and a
    /// validator fn, inline-expanded into one CHECK. Additive under
    /// `spock: "v0"`; parallel to `uniques`.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub checks: Vec<TableCheck>,
    /// The identity anchor (RFD 0014): `true` on the one `auth table`. Its
    /// single scalar key is what `spock_actor()` returns and `= me` stamps.
    /// Additive under `spock: "v0"` — `default` keeps pre-actor JSON loading.
    #[serde(default, skip_serializing_if = "std::ops::Not::not")]
    pub anchor: bool,
    /// Derived errors (§6.1). Never hand-written.
    pub errors: Vec<DerivedError>,
}

/// A row check (RFD 0013): a validator fn applied to a field group.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct TableCheck {
    pub fields: Vec<String>,
    #[serde(rename = "fn")]
    pub fn_name: String,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Field {
    pub name: String,
    #[serde(rename = "type")]
    pub ty: Type,
    pub optional: bool,
    pub unique: bool,
    pub default: Option<DefaultValue>,
    /// A field-level validator fn (RFD 0013): its name, inline-expanded
    /// into a `<table>_<field>_invalid` CHECK. Additive under `spock: "v0"`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub check: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum Type {
    Text,
    Int,
    Float,
    Bool,
    Timestamp,
    Uuid,
    /// The field holds the key of a row of `table`.
    Ref {
        table: String,
        on_delete: OnDelete,
    },
    /// A closed-set text refinement: the value is one of `values` (RFD
    /// 0013). Storage is TEXT; membership is enforced by a derived
    /// `<table>_<field>_invalid` CHECK and, on the floor write path, by a
    /// pre-engine membership check. Never reachable through a `Ref` — a
    /// set type may not be a key (E043), so `value_type` never yields it
    /// via a reference. Additive under `spock: "v0"`: a consumer that does
    /// not know `kind: "set"` rejects it rather than guessing (§6).
    Set {
        values: Vec<String>,
    },
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum OnDelete {
    Restrict,
    Cascade,
    /// Deleting the target nulls this field. Optional references only
    /// (E040); never derives a `restricted` error — it blocks nothing.
    #[serde(rename = "set_null")]
    SetNull,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum DefaultValue {
    /// UUIDv7 generated by the runtime at insert.
    Auto,
    /// UTC now captured by the runtime at insert.
    Now,
    Str {
        value: String,
    },
    Int {
        value: i64,
    },
    Float {
        value: f64,
    },
    Bool {
        value: bool,
    },
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct DerivedError {
    pub code: String,
    pub kind: ErrorKind,
    pub fields: Vec<String>,
    pub status: u16,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ErrorKind {
    Key,
    Unique,
    Required,
    RefNotFound,
    Restricted,
    /// A value-constraint violation (RFD 0013): a closed-set membership
    /// miss or a validator-fn `check` failure. Status 422 — intrinsic to
    /// the payload, not a conflict with existing state.
    Invalid,
}

/// A named wire shape (§3): scalar fields only — SQL result columns are
/// scalars, so this is a fact, not a restriction.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Record {
    pub name: String,
    pub fields: Vec<RecordField>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct RecordField {
    pub name: String,
    #[serde(rename = "type")]
    pub ty: Type,
    pub optional: bool,
}

/// A declared function (§7.4): the contract half is the language's
/// (name, params, return shape, declared errors); the body is the SQL
/// escape, carried verbatim and validated by the engine at load.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct FnDef {
    pub name: String,
    /// True for unmarked (read) fns: the engine rejects writing
    /// statements at load, execution uses a read transaction, and the
    /// fn surfaces on the GraphQL Query root (§7.4, RFD 0012). Pre-v2
    /// contract JSON has no field — `false` keeps every pre-v2 fn the
    /// mutation it always was (§6 additive law).
    #[serde(default)]
    pub readonly: bool,
    pub params: Vec<FnParam>,
    pub returns: FnReturn,
    /// Declared error codes (`! a | b`) — metadata for introspection and
    /// clients; the runtime surfaces undeclared errors truthfully too.
    /// Refusals (see below) are included: `errors` is the full declared
    /// failure surface.
    pub errors: Vec<String>,
    /// The subset of `errors` this fn *mints* (RFD 0012 §2.3): codes
    /// backed by no constraint, raised from the body via
    /// `spock_refuse('<code>')` and routed only if declared here. Pre-v2
    /// JSON has no field; empty is correct — nothing was minted.
    #[serde(default)]
    pub refusals: Vec<String>,
    /// The escape body: SQL statements in execution order, each exactly
    /// one statement; the last produces the return value (§7.4). Pre-v2
    /// contract JSON carried a single bare string — the deserializer
    /// accepts it as a one-statement body (§6 additive law).
    #[serde(deserialize_with = "sql_one_or_many")]
    pub sql: Vec<String>,
}

/// Accept `"sql": "..."` (pre-multi-statement JSON) as `["..."]`.
fn sql_one_or_many<'de, D>(deserializer: D) -> Result<Vec<String>, D::Error>
where
    D: serde::Deserializer<'de>,
{
    #[derive(Deserialize)]
    #[serde(untagged)]
    enum OneOrMany {
        One(String),
        Many(Vec<String>),
    }
    Ok(match OneOrMany::deserialize(deserializer)? {
        OneOrMany::One(s) => vec![s],
        OneOrMany::Many(v) => v,
    })
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct FnParam {
    pub name: String,
    /// Reuses [`Type`]; a ref param binds the target key's scalar. The
    /// `on_delete` a ref carries is inert here (params delete nothing).
    #[serde(rename = "type")]
    pub ty: Type,
    pub optional: bool,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct FnReturn {
    pub arity: FnArity,
    /// A table or record name — or, when `scalar` is set, a builtin
    /// scalar type name (`"int"`, `"text"`, …).
    pub of: String,
    /// True for scalar returns (`-> int`). Additive under `spock: "v0"` —
    /// `default` keeps pre-scalar contract JSON deserializable.
    #[serde(default)]
    pub scalar: bool,
}

impl FnReturn {
    /// The scalar type of a `scalar` return, `None` for shape returns.
    pub fn scalar_type(&self) -> Option<Type> {
        if !self.scalar {
            return None;
        }
        builtin_scalar(&self.of)
    }
}

/// The reserved non-derived error codes (§6.1) — protocol-owned, frozen
/// for v0.x. The one home: the checker's `!`-clause vocabulary and the
/// TS emission both read from here, so the set cannot drift per crate.
pub const RESERVED_CODES: [&str; 5] = [
    "not_found",
    "type_mismatch",
    "unknown_field",
    "bad_request",
    "internal",
];

/// Resolve a builtin scalar type name (as `FnReturn::of` carries it).
/// Type keywords can never name a table or record, so the namespace is
/// collision-free.
pub fn builtin_scalar(name: &str) -> Option<Type> {
    Some(match name {
        "text" => Type::Text,
        "int" => Type::Int,
        "float" => Type::Float,
        "bool" => Type::Bool,
        "timestamp" => Type::Timestamp,
        "uuid" => Type::Uuid,
        _ => return None,
    })
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum FnArity {
    /// `-> t`: exactly one row; zero is `not_found`, more is `internal`.
    One,
    /// `-> t?`: zero or one row; zero is `null`.
    Maybe,
    /// `-> [t]`: any number of rows; the author owns `LIMIT`.
    Many,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct SeedRow {
    pub table: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub binding: Option<String>,
    pub fields: BTreeMap<String, SeedValue>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SeedValue {
    /// Reference to an earlier seed row's binding. Tried first: it is the
    /// only object-shaped seed value.
    Ref {
        #[serde(rename = "ref")]
        binding: String,
    },
    Str(String),
    Int(i64),
    /// Tried after `Int`: an untagged whole number stays an integer.
    Float(f64),
    Bool(bool),
}

impl Contract {
    pub fn table(&self, name: &str) -> Option<&Table> {
        self.tables.iter().find(|t| t.name == name)
    }

    pub fn record(&self, name: &str) -> Option<&Record> {
        self.records.iter().find(|r| r.name == name)
    }

    pub fn fn_def(&self, name: &str) -> Option<&FnDef> {
        self.fns.iter().find(|f| f.name == name)
    }

    /// The identity anchor table (RFD 0014), if one is declared (`auth
    /// table`). At most one exists (E-ACT01). `spock_actor()` returns its
    /// single scalar key (E-ACT02); `= me` stamps it.
    pub fn anchor(&self) -> Option<&Table> {
        self.tables.iter().find(|t| t.anchor)
    }

    /// The normalized `(name, type, optional)` field list of a fn output
    /// shape — a table or a record. One lookup shared by engine
    /// validation, execution row mapping, GraphQL, and the TS emission.
    pub fn output_fields(&self, of: &str) -> Option<Vec<(&str, &Type, bool)>> {
        if let Some(table) = self.table(of) {
            return Some(
                table
                    .fields
                    .iter()
                    .map(|f| (f.name.as_str(), &f.ty, f.optional))
                    .collect(),
            );
        }
        self.record(of).map(|record| {
            record
                .fields
                .iter()
                .map(|f| (f.name.as_str(), &f.ty, f.optional))
                .collect()
        })
    }

    /// Reference fields across the contract that point at `target`,
    /// as `(referencing table, referencing field)`.
    pub fn inbound_refs(&self, target: &str) -> Vec<(&Table, &Field)> {
        self.tables
            .iter()
            .flat_map(|t| t.fields.iter().map(move |f| (t, f)))
            .filter(|(_, f)| matches!(&f.ty, Type::Ref { table, .. } if table == target))
            .collect()
    }

    /// Resolve the *storage* type a value of `ty` bottoms out at, chasing
    /// reference chains. Key-cycle-free by the checker (E017).
    pub fn storage_type(&self, ty: &Type) -> StorageType {
        match ty {
            Type::Text | Type::Uuid | Type::Timestamp | Type::Set { .. } => StorageType::Text,
            Type::Int => StorageType::Integer,
            Type::Float => StorageType::Real,
            Type::Bool => StorageType::Integer,
            Type::Ref { table, .. } => {
                let target = self.table(table).expect("checked: ref target exists");
                let key_field = target.field(&target.key[0]).expect("checked: key exists");
                self.storage_type(&key_field.ty)
            }
        }
    }

    /// Resolve the *value* type a field bottoms out at — the type that
    /// governs wire validation. For refs this is the target key's type.
    pub fn value_type<'a>(&'a self, ty: &'a Type) -> &'a Type {
        match ty {
            Type::Ref { table, .. } => {
                let target = self.table(table).expect("checked: ref target exists");
                let key_field = target.field(&target.key[0]).expect("checked: key exists");
                self.value_type(&key_field.ty)
            }
            other => other,
        }
    }
}

impl Table {
    pub fn field(&self, name: &str) -> Option<&Field> {
        self.fields.iter().find(|f| f.name == name)
    }

    /// The key field, if the key is a single field.
    pub fn single_key(&self) -> Option<&Field> {
        match self.key.as_slice() {
            [only] => self.field(only),
            _ => None,
        }
    }

    /// Look up the derived error for a kind and field set (§6.1).
    pub fn error_for(&self, kind: ErrorKind, fields: &[&str]) -> Option<&DerivedError> {
        self.errors.iter().find(|e| {
            e.kind == kind
                && e.fields
                    .iter()
                    .map(String::as_str)
                    .eq(fields.iter().copied())
        })
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum StorageType {
    Text,
    Integer,
    Real,
}

impl StorageType {
    pub fn sql(self) -> &'static str {
        match self {
            StorageType::Text => "TEXT",
            StorageType::Integer => "INTEGER",
            StorageType::Real => "REAL",
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn contract_serde_roundtrip() {
        let contract = Contract {
            spock: "v0".into(),
            tables: vec![Table {
                name: "user".into(),
                key: vec!["id".into()],
                fields: vec![
                    Field {
                        name: "id".into(),
                        ty: Type::Uuid,
                        optional: false,
                        unique: false,
                        default: Some(DefaultValue::Auto),
                        check: None,
                    },
                    Field {
                        name: "invited_by".into(),
                        ty: Type::Ref {
                            table: "user".into(),
                            on_delete: OnDelete::Restrict,
                        },
                        optional: true,
                        unique: false,
                        default: None,
                        check: None,
                    },
                ],
                uniques: vec![],
                checks: vec![],
                anchor: false,
                errors: vec![DerivedError {
                    code: "user_already_exists".into(),
                    kind: ErrorKind::Key,
                    fields: vec!["id".into()],
                    status: 409,
                }],
            }],
            records: vec![Record {
                name: "stats".into(),
                fields: vec![RecordField {
                    name: "posts".into(),
                    ty: Type::Int,
                    optional: false,
                }],
            }],
            fns: vec![FnDef {
                readonly: false,
                name: "rename_user".into(),
                params: vec![
                    FnParam {
                        name: "user".into(),
                        ty: Type::Ref {
                            table: "user".into(),
                            on_delete: OnDelete::Restrict,
                        },
                        optional: false,
                    },
                    FnParam {
                        name: "name".into(),
                        ty: Type::Text,
                        optional: false,
                    },
                ],
                returns: FnReturn {
                    arity: FnArity::One,
                    of: "user".into(),
                    scalar: false,
                },
                errors: vec!["user_username_taken".into()],
                refusals: vec![],
                sql: vec!["UPDATE user SET username = :name WHERE id = :user RETURNING *".into()],
            }],
            seed: vec![SeedRow {
                table: "user".into(),
                binding: Some("maya".into()),
                fields: BTreeMap::from([
                    ("username".into(), SeedValue::Str("maya".into())),
                    (
                        "invited_by".into(),
                        SeedValue::Ref {
                            binding: "luis".into(),
                        },
                    ),
                ]),
            }],
        };

        let json = serde_json::to_string_pretty(&contract).unwrap();
        // normative shapes (§6)
        assert!(json.contains("\"kind\": \"uuid\""));
        assert!(json.contains("\"kind\": \"ref\""));
        assert!(json.contains("\"on_delete\": \"restrict\""));
        assert!(json.contains("\"kind\": \"auto\""));
        assert!(json.contains("\"ref\": \"luis\""));
        assert!(json.contains("\"arity\": \"one\""));
        // the body serializes as a statement array (§6: pre-v2 JSON
        // carried a bare string; see legacy_contract_json_deserializes)
        assert!(json.contains("\"UPDATE user"));

        let back: Contract = serde_json::from_str(&json).unwrap();
        assert_eq!(back.tables[0].name, "user");
        assert_eq!(back.fns[0].errors, vec!["user_username_taken"]);
        assert_eq!(back.records[0].fields[0].name, "posts");
        assert!(matches!(
            back.seed[0].fields.get("invited_by"),
            Some(SeedValue::Ref { binding }) if binding == "luis"
        ));
        assert!(matches!(
            back.seed[0].fields.get("username"),
            Some(SeedValue::Str(s)) if s == "maya"
        ));
    }

    /// A closed-set type serializes as `{"kind":"set","values":[...]}` and
    /// round-trips (RFD 0013 §7 — additive under `spock: "v0"`).
    #[test]
    fn set_type_serde_roundtrip() {
        let ty = Type::Set {
            values: vec!["pending".into(), "ready".into()],
        };
        let json = serde_json::to_string(&ty).unwrap();
        assert_eq!(json, r#"{"kind":"set","values":["pending","ready"]}"#);
        let back: Type = serde_json::from_str(&json).unwrap();
        assert_eq!(back, ty);
    }

    /// A contract serialized before `fns`/`records` existed still loads —
    /// the §6 additive-only freeze, proven.
    #[test]
    fn legacy_contract_json_deserializes() {
        let legacy = r#"{ "spock": "v0", "tables": [], "seed": [] }"#;
        let contract: Contract = serde_json::from_str(legacy).unwrap();
        assert!(contract.fns.is_empty());
        assert!(contract.records.is_empty());

        // pre-scalar fn JSON (no `returns.scalar` key, bare-string `sql`)
        // still loads too — the string becomes a one-statement body
        let pre_scalar = r#"{ "spock": "v0", "tables": [], "seed": [], "fns": [
            { "name": "f", "params": [],
              "returns": { "arity": "one", "of": "user" },
              "errors": [], "sql": "S" } ] }"#;
        let contract: Contract = serde_json::from_str(pre_scalar).unwrap();
        assert!(!contract.fns[0].returns.scalar);
        assert_eq!(contract.fns[0].sql, vec!["S"]);
        // pre-v2 fns: never a read, nothing minted
        assert!(!contract.fns[0].readonly);
        assert!(contract.fns[0].refusals.is_empty());
    }
}
