//! The compiled contract (docs/spec/v0.md §6) — the interchange artifact.
//!
//! Everything a runtime or tool needs is in [`Contract`]; nothing refers back
//! to source text. Serialization shape is normative (§6).

use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Contract {
    /// Language version tag; `"v0"`.
    pub spock: String,
    pub tables: Vec<Table>,
    /// Named wire shapes (fn returns). Additive under `spock: "v0"` —
    /// `default` keeps pre-record contract JSON deserializable.
    #[serde(default)]
    pub records: Vec<Record>,
    /// The deliberate surface: declared functions with SQL-escape bodies.
    /// Additive under `spock: "v0"`.
    #[serde(default)]
    pub fns: Vec<FnDef>,
    pub seed: Vec<SeedRow>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Table {
    pub name: String,
    /// Key field names, declaration order.
    pub key: Vec<String>,
    pub fields: Vec<Field>,
    /// Multi-field unique groups (single-field uniques live on the field).
    pub uniques: Vec<Vec<String>>,
    /// Derived errors (§6.1). Never hand-written.
    pub errors: Vec<DerivedError>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Field {
    pub name: String,
    #[serde(rename = "type")]
    pub ty: Type,
    pub optional: bool,
    pub unique: bool,
    pub default: Option<DefaultValue>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum Type {
    Text,
    Int,
    Float,
    Bool,
    Timestamp,
    Uuid,
    /// The field holds the key of a row of `table`.
    Ref {
        table: String,
        on_delete: OnDelete,
    },
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum OnDelete {
    Restrict,
    Cascade,
    /// Deleting the target nulls this field. Optional references only
    /// (E040); never derives a `restricted` error — it blocks nothing.
    #[serde(rename = "set_null")]
    SetNull,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum DefaultValue {
    /// UUIDv7 generated by the runtime at insert.
    Auto,
    /// UTC now captured by the runtime at insert.
    Now,
    Str {
        value: String,
    },
    Int {
        value: i64,
    },
    Float {
        value: f64,
    },
    Bool {
        value: bool,
    },
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct DerivedError {
    pub code: String,
    pub kind: ErrorKind,
    pub fields: Vec<String>,
    pub status: u16,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ErrorKind {
    Key,
    Unique,
    Required,
    RefNotFound,
    Restricted,
}

/// A named wire shape (§3): scalar fields only — SQL result columns are
/// scalars, so this is a fact, not a restriction.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Record {
    pub name: String,
    pub fields: Vec<RecordField>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct RecordField {
    pub name: String,
    #[serde(rename = "type")]
    pub ty: Type,
    pub optional: bool,
}

/// A declared function (§7.4): the contract half is the language's
/// (name, params, return shape, declared errors); the body is the SQL
/// escape, carried verbatim and validated by the engine at load.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct FnDef {
    pub name: String,
    pub params: Vec<FnParam>,
    pub returns: FnReturn,
    /// Declared error codes (`! a | b`) — metadata for introspection and
    /// clients; the runtime surfaces undeclared errors truthfully too.
    pub errors: Vec<String>,
    /// The escape body: exactly one SQL statement.
    pub sql: String,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct FnParam {
    pub name: String,
    /// Reuses [`Type`]; a ref param binds the target key's scalar. The
    /// `on_delete` a ref carries is inert here (params delete nothing).
    #[serde(rename = "type")]
    pub ty: Type,
    pub optional: bool,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct FnReturn {
    pub arity: FnArity,
    /// A table or record name — or, when `scalar` is set, a builtin
    /// scalar type name (`"int"`, `"text"`, …).
    pub of: String,
    /// True for scalar returns (`-> int`). Additive under `spock: "v0"` —
    /// `default` keeps pre-scalar contract JSON deserializable.
    #[serde(default)]
    pub scalar: bool,
}

impl FnReturn {
    /// The scalar type of a `scalar` return, `None` for shape returns.
    pub fn scalar_type(&self) -> Option<Type> {
        if !self.scalar {
            return None;
        }
        builtin_scalar(&self.of)
    }
}

/// Resolve a builtin scalar type name (as `FnReturn::of` carries it).
/// Type keywords can never name a table or record, so the namespace is
/// collision-free.
pub fn builtin_scalar(name: &str) -> Option<Type> {
    Some(match name {
        "text" => Type::Text,
        "int" => Type::Int,
        "float" => Type::Float,
        "bool" => Type::Bool,
        "timestamp" => Type::Timestamp,
        "uuid" => Type::Uuid,
        _ => return None,
    })
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum FnArity {
    /// `-> t`: exactly one row; zero is `not_found`, more is `internal`.
    One,
    /// `-> t?`: zero or one row; zero is `null`.
    Maybe,
    /// `-> [t]`: any number of rows; the author owns `LIMIT`.
    Many,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct SeedRow {
    pub table: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub binding: Option<String>,
    pub fields: BTreeMap<String, SeedValue>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SeedValue {
    /// Reference to an earlier seed row's binding. Tried first: it is the
    /// only object-shaped seed value.
    Ref {
        #[serde(rename = "ref")]
        binding: String,
    },
    Str(String),
    Int(i64),
    /// Tried after `Int`: an untagged whole number stays an integer.
    Float(f64),
    Bool(bool),
}

impl Contract {
    pub fn table(&self, name: &str) -> Option<&Table> {
        self.tables.iter().find(|t| t.name == name)
    }

    pub fn record(&self, name: &str) -> Option<&Record> {
        self.records.iter().find(|r| r.name == name)
    }

    pub fn fn_def(&self, name: &str) -> Option<&FnDef> {
        self.fns.iter().find(|f| f.name == name)
    }

    /// The normalized `(name, type, optional)` field list of a fn output
    /// shape — a table or a record. One lookup shared by engine
    /// validation, execution row mapping, GraphQL, and the TS emission.
    pub fn output_fields(&self, of: &str) -> Option<Vec<(&str, &Type, bool)>> {
        if let Some(table) = self.table(of) {
            return Some(
                table
                    .fields
                    .iter()
                    .map(|f| (f.name.as_str(), &f.ty, f.optional))
                    .collect(),
            );
        }
        self.record(of).map(|record| {
            record
                .fields
                .iter()
                .map(|f| (f.name.as_str(), &f.ty, f.optional))
                .collect()
        })
    }

    /// Reference fields across the contract that point at `target`,
    /// as `(referencing table, referencing field)`.
    pub fn inbound_refs(&self, target: &str) -> Vec<(&Table, &Field)> {
        self.tables
            .iter()
            .flat_map(|t| t.fields.iter().map(move |f| (t, f)))
            .filter(|(_, f)| matches!(&f.ty, Type::Ref { table, .. } if table == target))
            .collect()
    }

    /// Resolve the *storage* type a value of `ty` bottoms out at, chasing
    /// reference chains. Key-cycle-free by the checker (E017).
    pub fn storage_type(&self, ty: &Type) -> StorageType {
        match ty {
            Type::Text | Type::Uuid | Type::Timestamp => StorageType::Text,
            Type::Int => StorageType::Integer,
            Type::Float => StorageType::Real,
            Type::Bool => StorageType::Integer,
            Type::Ref { table, .. } => {
                let target = self.table(table).expect("checked: ref target exists");
                let key_field = target.field(&target.key[0]).expect("checked: key exists");
                self.storage_type(&key_field.ty)
            }
        }
    }

    /// Resolve the *value* type a field bottoms out at — the type that
    /// governs wire validation. For refs this is the target key's type.
    pub fn value_type<'a>(&'a self, ty: &'a Type) -> &'a Type {
        match ty {
            Type::Ref { table, .. } => {
                let target = self.table(table).expect("checked: ref target exists");
                let key_field = target.field(&target.key[0]).expect("checked: key exists");
                self.value_type(&key_field.ty)
            }
            other => other,
        }
    }
}

impl Table {
    pub fn field(&self, name: &str) -> Option<&Field> {
        self.fields.iter().find(|f| f.name == name)
    }

    /// The key field, if the key is a single field.
    pub fn single_key(&self) -> Option<&Field> {
        match self.key.as_slice() {
            [only] => self.field(only),
            _ => None,
        }
    }

    /// Look up the derived error for a kind and field set (§6.1).
    pub fn error_for(&self, kind: ErrorKind, fields: &[&str]) -> Option<&DerivedError> {
        self.errors.iter().find(|e| {
            e.kind == kind
                && e.fields
                    .iter()
                    .map(String::as_str)
                    .eq(fields.iter().copied())
        })
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum StorageType {
    Text,
    Integer,
    Real,
}

impl StorageType {
    pub fn sql(self) -> &'static str {
        match self {
            StorageType::Text => "TEXT",
            StorageType::Integer => "INTEGER",
            StorageType::Real => "REAL",
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn contract_serde_roundtrip() {
        let contract = Contract {
            spock: "v0".into(),
            tables: vec![Table {
                name: "user".into(),
                key: vec!["id".into()],
                fields: vec![
                    Field {
                        name: "id".into(),
                        ty: Type::Uuid,
                        optional: false,
                        unique: false,
                        default: Some(DefaultValue::Auto),
                    },
                    Field {
                        name: "invited_by".into(),
                        ty: Type::Ref {
                            table: "user".into(),
                            on_delete: OnDelete::Restrict,
                        },
                        optional: true,
                        unique: false,
                        default: None,
                    },
                ],
                uniques: vec![],
                errors: vec![DerivedError {
                    code: "user_already_exists".into(),
                    kind: ErrorKind::Key,
                    fields: vec!["id".into()],
                    status: 409,
                }],
            }],
            records: vec![Record {
                name: "stats".into(),
                fields: vec![RecordField {
                    name: "posts".into(),
                    ty: Type::Int,
                    optional: false,
                }],
            }],
            fns: vec![FnDef {
                name: "rename_user".into(),
                params: vec![
                    FnParam {
                        name: "user".into(),
                        ty: Type::Ref {
                            table: "user".into(),
                            on_delete: OnDelete::Restrict,
                        },
                        optional: false,
                    },
                    FnParam {
                        name: "name".into(),
                        ty: Type::Text,
                        optional: false,
                    },
                ],
                returns: FnReturn {
                    arity: FnArity::One,
                    of: "user".into(),
                    scalar: false,
                },
                errors: vec!["user_username_taken".into()],
                sql: "UPDATE user SET username = :name WHERE id = :user RETURNING *".into(),
            }],
            seed: vec![SeedRow {
                table: "user".into(),
                binding: Some("maya".into()),
                fields: BTreeMap::from([
                    ("username".into(), SeedValue::Str("maya".into())),
                    (
                        "invited_by".into(),
                        SeedValue::Ref {
                            binding: "luis".into(),
                        },
                    ),
                ]),
            }],
        };

        let json = serde_json::to_string_pretty(&contract).unwrap();
        // normative shapes (§6)
        assert!(json.contains("\"kind\": \"uuid\""));
        assert!(json.contains("\"kind\": \"ref\""));
        assert!(json.contains("\"on_delete\": \"restrict\""));
        assert!(json.contains("\"kind\": \"auto\""));
        assert!(json.contains("\"ref\": \"luis\""));
        assert!(json.contains("\"arity\": \"one\""));
        assert!(json.contains("\"sql\": \"UPDATE user"));

        let back: Contract = serde_json::from_str(&json).unwrap();
        assert_eq!(back.tables[0].name, "user");
        assert_eq!(back.fns[0].errors, vec!["user_username_taken"]);
        assert_eq!(back.records[0].fields[0].name, "posts");
        assert!(matches!(
            back.seed[0].fields.get("invited_by"),
            Some(SeedValue::Ref { binding }) if binding == "luis"
        ));
        assert!(matches!(
            back.seed[0].fields.get("username"),
            Some(SeedValue::Str(s)) if s == "maya"
        ));
    }

    /// A contract serialized before `fns`/`records` existed still loads —
    /// the §6 additive-only freeze, proven.
    #[test]
    fn legacy_contract_json_deserializes() {
        let legacy = r#"{ "spock": "v0", "tables": [], "seed": [] }"#;
        let contract: Contract = serde_json::from_str(legacy).unwrap();
        assert!(contract.fns.is_empty());
        assert!(contract.records.is_empty());

        // pre-scalar fn JSON (no `returns.scalar` key) still loads too
        let pre_scalar = r#"{ "spock": "v0", "tables": [], "seed": [], "fns": [
            { "name": "f", "params": [],
              "returns": { "arity": "one", "of": "user" },
              "errors": [], "sql": "S" } ] }"#;
        let contract: Contract = serde_json::from_str(pre_scalar).unwrap();
        assert!(!contract.fns[0].returns.scalar);
    }
}
